### ISSUE TITLE
Add this to bower registry

### ISSUE THREAD

**Issue by comzeradd** [mozilla/mofo-bootstrap#105]
It would be nice if this was included at [Bower](https://bower.io/) as well. This would make it easier for non-node projects to include and use the theme as part of their frontend dependencies workflow.

**Comment by alanmoo** [comment]
A project doesn't have to be node-based to use npm. Since Bower is installed by npm, that means you have npm installed already and could directly use it. What's the benefit of using Bower instead of npm for dependency management these days?

**Comment by comzeradd** [comment]
In theory you can use npm for frontend dependencies, but it's not optimal. You'll see even node projects that use both tools to separate backend and frontend libraries. The reason is that bower is tailored for frontend dependencies specifically and is optimized around this use case (eg. more lightweight, flat dependencies resolving). 

I understand if this is not a priority. I was just curious if it's has been considered. It would be easier for non-node projects (eg. django, flask) that want to use this theme to include it to their existing workflow.

**Comment by alanmoo** [comment]
I'm not opposed to this, but I'm also not convinced it's necessary. If anything, perhaps our single Bootstrap dependency can be moved to `devDependencies` so it is indeed flat. If @gvn's good with it, I'd say we'd accept a PR for Bower support.

**Comment by gvn** [comment]
Hi @comzeradd. Thanks for your thoughts. Since this is a library intended for internal Mozilla Foundation development and we don't use Bower, I don't feel like we should add it to the registry. That signals an intent that we will always ensure Bower compatibility, which isn't the case. It also signals that it's intended for general usage for non-Mozilla work, which is also false.

**Comment by alanmoo** [comment]
He is referring to Mozilla work
