### ISSUE TITLE
Text overflows on small screen devices.

### ISSUE THREAD

**Issue by dhiraj161298** [mozilla/mofo-bootstrap#108]
As stated [here](https://github.com/mozilla/science.mozilla.org/issues/582#issuecomment-284156331) The text with h2 (and also h1 tags) overflow on small screen devices.

![ca0d8f7e-00db-11e7-80fa-1bab8cebd77c](https://cloud.githubusercontent.com/assets/4402679/23580025/a1012a2a-011f-11e7-8431-8369cabdb204.png)

**Comment by alanmoo** [comment]
This specific case has to do with the word length. While it's not an exceptionally long word, I believe this is an issue to be addressed in the science repo. If you want to discuss viewport based typograhy, check if any issues exist within this repo (or Bootstrap itself). If not, go ahead and open one. I've felt like it's something we could make use of, but it takes a lot of coordination to get it right.
