### ISSUE TITLE
Integrate Mofo colour thinking

### ISSUE THREAD

**Issue by cassiemc** [mozilla/mofo-bootstrap#28]
We will soon have a refined Mofo-wide colour palette based on @kristinashu's [awesome work here](https://github.com/MozillaFoundation/Design/issues/139) which we'll need to integrate with Foxlight.

**Comment by cassiemc** [comment]
Who's the owner for this? @vazquez @gvn? The design team is going to test @kristinashu's current palette proposal. Those tickets can be tracked here: https://github.com/MozillaFoundation/Design/issues?q=is%3Aissue+is%3Aopen+label%3Acolour

@hannahkane should we postpone this to the next heartbeat? We should be in a better place to do this more finally at some point next week.

**Comment by hannahkane** [comment]
Fine with me to to postpone, though this heartbeat does go until the end of next week.

**Comment by cassiemc** [comment]
Yeah if the designers get to it and yield results soon I should think we will be able to implement it fairly quickly.

**Comment by gvn** [comment]
It should be pretty quick to add it once the colors are finalized. :+1:

**Comment by cassiemc** [comment]
Cool! Assigning to you @gvn, feel free to undo if that's not accurate.

**Comment by kristinashu** [comment]
Opened https://github.com/mozilla/mofo-bootstrap/issues/89 and closing this ticket.
