### ISSUE TITLE
Give tool a functional name we love

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/mofo-bootstrap#59]
Hi team, I heard there's been some naming struggles over here. Despite the risk of becoming *very unpopular*, I'd like to help. 

**Proposed name** –– Foundation Style

**Boring?!** –– Yes. And very descriptive, twice. Easy for new hires, contributors, and other staff to understand. No need to make it hard. 

**Change it again?! Now?!** –– It will only get harder later. I received an email yesterday that included Mattermost, Mattermoz, and chat.mozillafoundation.org. It'll take many bugs and heartbeats to untangle that so we can on-board people in a way that doesn't handicap the platform's chances for success. 

**Where's the fun?!** –– We can give our versions quirky names. Call Version 1 the onesie edition if we want. 

@hannahkane @simonwex @gvn @vazquez @cassiemc - please vote below and cc anyone else who should be on this thread.

**Comment by xmatthewx** [comment]
Trouble like this happens because we often name a thing too early in the process. In prep for Mozilla Co's innovation initiatives, they introduced a naming convention. Every new project is called Project_______ until it graduates beyond experiment. Names can be anything, but never include Moz, Fox, or Fire. Post graduation, the project gets a good name based everything learned during prototyping and market research if needed.

**Comment by gvn** [comment]
There's already a CSS framework called [Foundation](http://foundation.zurb.com/), so I think that's confusing give that this is a Bootstrap theme.

**Comment by gvn** [comment]
See also: Issues #54 and #31

**Comment by xmatthewx** [comment]
Thanks for the context @gvn. I'd only heard about the name change in conversation. It's never an easy thing, but I think it's important to get right. 

Foundation might not be the right answer, but I'd still choose a descriptive name over something that doesn't have any meaning. 

leadwithstyle
openstyle
networkstyle

**Comment by gvn** [comment]
Going with `mofo-bootstrap`
