### ISSUE TITLE
Remove colour shades from the demo page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mofo-bootstrap#61]
https://mozilla.github.io/mozmaker/demo/
for example,
<img width="933" alt="screen shot 2016-03-31 at 11 07 06 am" src="https://cloud.githubusercontent.com/assets/2896608/14185917/bf389d38-f730-11e5-8ef8-2695ff614c27.png">

Since the shades aren't part of the style guide / `mozmaker.css`, we should remove them from the demo page.

**Comment by xmatthewx** [comment]
I might be mistaken, but I believe there will be recommended shades.  cc @kristinashu @vazquez

**Comment by kristinashu** [comment]
I'm not too sure what you mean? These are the 'final' color and they all have different tints https://redpen.io/aq798f74c9a3ad7266

**Comment by xmatthewx** [comment]
Maybe the final colors haven't been added to the style sheet. @vazquez ?

**Comment by gvn** [comment]
The base colors (what you see as 100%) are all set as named variables, so you can reference `$dino-red` or `$market-orange` in Sass that extends Mozmaker.

The variations shown are just Sass filters on those base colors, so there's not a ton of added value showing them off. We can leave them in or take them out IMO.

**Comment by kristinashu** [comment]
I think it's valuable to show the different colour tints since we want people to use them.
