### ISSUE TITLE
Rename to mofo-bootstrap

### ISSUE THREAD

**Issue by gvn** [mozilla/mofo-bootstrap#69]
With blessings from @simonwex I'm going to give this library a semantic name: `mofo-bootstrap`.

- [x] change all source based instances of `mozmaker` to `mofo-bootstrap`
- [x] rename repo
- [x] publish new npm module `mofo-bootstrap`
- [x] add [deprecation warning](https://docs.npmjs.com/cli/deprecate) to `mozmaker` npm module
- [x] migrate `mozmaker` consumers to `mofo-bootstrap`

**Comment by xmatthewx** [comment]
cc @kristinashu to update universal design docs. farewell [onesie](https://www.youtube.com/watch?v=9NVvNBCg5fM).

**Comment by simonwex** [comment]
@gvn your christmas present this year is still going to be a fox onesie.
