### ISSUE TITLE
Colour updates

### ISSUE THREAD

**Issue by kristinashu** [mozilla/mofo-bootstrap#89]
Final colours the design team settled on (https://github.com/MozillaFoundation/Design/issues/139) are slightly different than what appears on the [demo page](https://mozilla.github.io/mofo-bootstrap/demo/).

We have https://redpen.io/aq798f74c9a3ad7266
<img width="1012" alt="red-pen-795c21c7-82b8-4e28-e37d-2868c2c4a7fe" src="https://cloud.githubusercontent.com/assets/1068783/20328017/e09001ce-ab44-11e6-80ad-ef1dcaed6c4a.png">

**How we came to get those colours:**
We adjusted the base hex values and then used LESS to create the three other tints of that same colour. 

Luke created a handy tool to test out the colours http://flukeout.github.io/color-generator/
and http://flukeout.github.io/master-template/style-guide/?theme=theme-march-14

For Sketch files, we then ink dropped the generated tints to get the hex values.

We also found we needed more grey tints.

**Question:**
@gvn @alanmoo how were the colours on the demo page generated? Are you using opacity? Does it make sense to update mofo-bootstrap so it generates colours using LESS?

cc @sabrinang @taisdesouzalessa

**Comment by gvn** [comment]
`mofo-bootstrap` uses Sass (which is now our standard CSS preprocessor).

The variations are done with `rgba` values.

**Comment by kristinashu** [comment]
So if we wanted to use the lightest blue over an image, would that work? Or would it be too transparent? If that's the case, can we use Sass to get the lighter colours as well?

**Comment by gvn** [comment]
We probably should use a color function other than changing opacity for the palette.

Sass can do a lot of color manipulations: http://sass-lang.com/documentation/Sass/Script/Functions.html

In this case, [lighten](http://sass-lang.com/documentation/Sass/Script/Functions.html#lighten-instance_method) looks like the right choice.

**Comment by alanmoo** [comment]
I regenerated the colors based on the Sass lighten/darken algorithms. They're slightly different but this'll make things a lot easier. Any concerns with using these instead? (Ignore the grays, I'll hard code those).

<img width="1223" alt="screenshot 2016-11-17 17 28 32" src="https://cloud.githubusercontent.com/assets/1682681/20410491/4f9f6490-aceb-11e6-9811-21fada962d59.png">

**Comment by kristinashu** [comment]
These look great!
