### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by kristinashu** [mozilla/mofo-bootstrap#92]
Footer design is quite established so this is ready to be added. Related design ticket https://github.com/MozillaFoundation/Design/issues/164

Not all footers would have all of these links and some might have new ones.

![320px - footer](https://cloud.githubusercontent.com/assets/1068783/20329167/79254d44-ab4b-11e6-80b0-95617723160c.png)
![480px - footer](https://cloud.githubusercontent.com/assets/1068783/20329169/792a196e-ab4b-11e6-9300-2c00f25cf1c8.png)
![850px - footer](https://cloud.githubusercontent.com/assets/1068783/20329168/79297018-ab4b-11e6-9ab4-840627e8eb02.png)
![1200px - footer](https://cloud.githubusercontent.com/assets/1068783/20329170/792a655e-ab4b-11e6-9c13-40d7d6c437e1.png)

Background grey should be: lightness -20%
<img width="814" alt="screen shot 2016-11-15 at 3 52 45 pm" src="https://cloud.githubusercontent.com/assets/1068783/20329197/a39649b6-ab4b-11e6-8627-6564ca21c000.png">

Icons can come from https://github.com/mozilla/mofo-bootstrap/issues/91

Footer is currently on:
- https://science.mozilla.org/ (good example)
- http://advocacy.mozilla.org/ (good example)
- https://mozilla.github.io/womenandweb/ (good example)
- https://thimble.mozilla.org/en-US/ (older iteration)
- https://goggles.mozilla.org/ (older iteration)
- https://equalrating.com/ (it's catching on!)

cc @gvn @alanmoo @sabrinang @taisdesouzalessa

**Comment by gvn** [comment]
Just a note that this should probably be a `mofo-ui` component.

**Comment by kristinashu** [comment]
@flukeout is possibly interested in styling this!

**Comment by mmmavis** [comment]
@gvn I can work on this today or tomorrow. I can't decide on this though - do you think the CSS code should be part of `mofo-bootstrap` or `mofo-ui`?

**Comment by alanmoo** [comment]
I might be missing some recent context, but I'd imagine this could be written completely without custom CSS. It should be in MoFo-UI either way though, as it is a component, and mofo-bootstrap is meant to just be a customized version of Bootstrap, last I recall us talking about it.

**Comment by gvn** [comment]
Just to recap:

@mmmavis Let's start by building the footer in `mofo-bootstrap` as a static "partial".

Since `mofo-bootstrap` is a dependency of `mofo-ui` we can later make a corresponding footer React component if we feel it is beneficial. The CSS for the React component would then come from `mofo-bootstrap`.

This way non-React projects can still use the shared footer CSS.

**Comment by mmmavis** [comment]
> mofo-bootstrap is meant to just be a customized version of Bootstrap

Ah good point. I was seeing `mofo-boostrap` more like just a shared MoFo styling thing.

@alanmoo @gvn should we override anything in https://github.com/twbs/bootstrap/blob/3f01134031b15a934d5e233bb26a407a7e05492b/docs/assets/scss/_footer.scss ? colours? sizing?

**Comment by gvn** [comment]
This is a brand new, non-Bootstrap partial, so you won't be overriding any existing stuff.

**Comment by alanmoo** [comment]
Sounds reasonable, though I'd really like to see this add as little CSS as possible, because I believe the Bootstrap 4 classes can handle almost all of this.

@mmmavis, looks like that scss file is in the docs directory, not part of bootstrap proper.

**Comment by gvn** [comment]
> Sounds reasonable, though I'd really like to see this add as little CSS as possible, because I believe the Bootstrap 4 classes can handle almost all of this.

Agreed.

**Comment by gvn** [comment]
Also just to clarify: yes, this is a departure from the intended "purity" of `mofo-bootstrap` being *just a Bootstrap theme*. However, given our diversity of needs (eg: mix of React and non-React projects) I think it's the best path to take.

**Comment by alanmoo** [comment]
For the footer specifically, I can see that. I do think there's a use case for a react component though, I've seen some variants on the footer that could be addressed by props being passed in. Or we need to be really strict about the design of the footer.

**Comment by gvn** [comment]
Yep, we can totally make it a React component as well. 👍 

Let's just start with the static version in `mofo-bootstrap`.

**Comment by mmmavis** [comment]
I'm thinking style and layout should stay the same. A React component on `mofo-ui` should be useful as we can allow sites to adjust footer links accordingly.

**Comment by mmmavis** [comment]
I'll start with `mofo-bootstrap` and have both of you review my PR. :clinking_glasses:

**Comment by mmmavis** [comment]
@kristinashu what colours should I use for regular text and links (default and hover state)?

**Comment by alanmoo** [comment]
Note that MoFo-Bootstrap has been updated. https://mozilla.github.io/mofo-bootstrap/demo/

(Any slight variances in the color codes are due to the difference in LESS and Sass's darken/lighten methods, but I used the same percentages to calculate them)

**Comment by kristinashu** [comment]
@mmmavis what you wrote sounds good!

**Comment by mmmavis** [comment]
@kristinashu or @taisdesouzalessa can either of you help consolidate all the footer icons that are used across our MoFo sites? 😉 :clinking_glasses:

**Comment by kristinashu** [comment]
@mmmavis here are all the icons: [footer icons.zip](https://github.com/mozilla/mofo-bootstrap/files/705403/footer.icons.zip)

I've also updated the comp with a few more icons and put them into a more logical order:

![1200px - footer](https://cloud.githubusercontent.com/assets/1068783/21946326/c253de82-d994-11e6-9103-27c93792216f.png)

**Comment by flukeout** [comment]
Will you be using the icon font for these? Hopefully you can give it a try! If you have issues or problems with it, or want me to add some icons that aren't there, I'd be happy to!

* https://mozilla.github.io/foundation-icons/

**Comment by kristinashu** [comment]
One more icon for Cookies:
[icon-cookies.svg.zip](https://github.com/mozilla/mofo-bootstrap/files/705541/icon-cookies.svg.zip)

**Comment by flukeout** [comment]
@gvn @alanmoo Are you planning or wanting to use the icon font in mofo-ui (or whatever will contain the footer component)?

Let me know your thoughts, I can help.

**Comment by gvn** [comment]
Hmm. There's a lot of icons in there that most sites won't use, so I'm not sure we should make `foundation-icons` a dependency of `mofo-bootstrap`.

How large is the font? How much more do we plan on adding? Are any projects currently using it?

I don't foresee `mofo-bootstrap` needing a ton of images. So far the footer is the only use case and it's kind of an outlier to begin with since it's a non-Bootstrap component.

**Comment by flukeout** [comment]
It's 46kb and does indeed have a ton of components. If you decide that an icon font is good practice for our needs, then I'm happy to trim & update the font. Otherwise, let's shelf it - it seems like a good thing for a mature / stable site or product, but it's a pain in the ass to update.

**Comment by alanmoo** [comment]
I think the ideal way to handle icons would be some way to only pull in the ones we use on a given site. No idea how we'd go about that though, probably via SVGs instead of font characters...

**Comment by kristinashu** [comment]
They haven't actually shared an svg version (or the font) for the new logo so might have to stick with the old one for now. Unless, @sabrinang do you have an svg version of the new logo?

**Comment by mmmavis** [comment]
That's fine. Can you link me to the current logo svg file? @kristinashu

**Comment by kristinashu** [comment]
@mmmavis here you go 
[Mozilla.svg.zip](https://github.com/mozilla/mofo-bootstrap/files/715360/Mozilla.svg.zip)

**Comment by kristinashu** [comment]
Sorry, we have the new logo now... can you please update with this one:

[logo-mozilla.svg.zip](https://github.com/mozilla/mofo-bootstrap/files/727585/logo-mozilla.svg.zip)

Please and thank you!

**Comment by gvn** [comment]
![itclap](https://cloud.githubusercontent.com/assets/206379/22488315/1ff1ee50-e7c6-11e6-83b9-2a6876927bb4.gif)
